before_install:
  - pip install pdfkit
  - pip install simplejson
language: node_js
script: "npm test"
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec